# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContactWindow(object):
    def setupUi(self, ContactWindow):
        ContactWindow.setObjectName("ContactWindow")
        ContactWindow.resize(638, 770)
        ContactWindow.setStyleSheet("background-color: rgb(170, 244, 255);")
        ContactWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        ContactWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tabWidget = QtWidgets.QTabWidget(ContactWindow)
        self.tabWidget.setGeometry(QtCore.QRect(0, 80, 641, 691))
        self.tabWidget.setStyleSheet("background-color: rgb(200, 255, 166);")
        self.tabWidget.setObjectName("tabWidget")
        self.Chat = QtWidgets.QWidget()
        self.Chat.setObjectName("Chat")
        self.send_text = QtWidgets.QPushButton(self.Chat)
        self.send_text.setGeometry(QtCore.QRect(550, 600, 81, 35))
        self.send_text.setStyleSheet("background-color: rgb(159, 156, 163);")
        self.send_text.setObjectName("send_text")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Chat)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 480, 621, 37))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.send_pic = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.send_pic.setStyleSheet("background-color: rgb(134, 255, 209);")
        self.send_pic.setObjectName("send_pic")
        self.horizontalLayout.addWidget(self.send_pic)
        self.send_file = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.send_file.setStyleSheet("background-color: rgb(255, 238, 176);")
        self.send_file.setObjectName("send_file")
        self.horizontalLayout.addWidget(self.send_file)
        self.send_video = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.send_video.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.send_video.setObjectName("send_video")
        self.horizontalLayout.addWidget(self.send_video)
        self.method = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.method.setStyleSheet("background-color: rgb(255, 130, 99);")
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.horizontalLayout.addWidget(self.method)
        self.input_text = QtWidgets.QTextEdit(self.Chat)
        self.input_text.setGeometry(QtCore.QRect(0, 520, 541, 111))
        self.input_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_text.setObjectName("input_text")
        self.msgs_widget = QtWidgets.QWidget(self.Chat)
        self.msgs_widget.setGeometry(QtCore.QRect(0, 0, 631, 471))
        self.msgs_widget.setObjectName("msgs_widget")
        self.scrollArea = QtWidgets.QScrollArea(self.msgs_widget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 631, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.msgs_contents = QtWidgets.QWidget()
        self.msgs_contents.setGeometry(QtCore.QRect(0, 0, 627, 467))
        self.msgs_contents.setObjectName("msgs_contents")
        self.msgs_box = QtWidgets.QGroupBox(self.msgs_contents)
        self.msgs_box.setGeometry(QtCore.QRect(0, 0, 631, 471))
        self.msgs_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.msgs_box.setTitle("")
        self.msgs_box.setObjectName("msgs_box")
        self.scrollArea.setWidget(self.msgs_box)
        self.tabWidget.addTab(self.Chat, "")
        self.Files = QtWidgets.QWidget()
        self.Files.setObjectName("Files")
        self.file_table = QtWidgets.QTableWidget(self.Files)
        self.file_table.setGeometry(QtCore.QRect(0, 0, 631, 631))
        self.file_table.setRowCount(0)
        self.file_table.setColumnCount(3)
        self.file_table.setObjectName("file_table")
        self.tabWidget.addTab(self.Files, "")
        self.contact_icon = QtWidgets.QLabel(ContactWindow)
        self.contact_icon.setGeometry(QtCore.QRect(10, 10, 70, 70))
        self.contact_icon.setScaledContents(True)
        self.contact_icon.setObjectName("contact_icon")
        self.contact_nickname = QtWidgets.QLabel(ContactWindow)
        self.contact_nickname.setGeometry(QtCore.QRect(100, 10, 281, 31))
        self.contact_nickname.setObjectName("contact_nickname")
        self.contact_email = QtWidgets.QLabel(ContactWindow)
        self.contact_email.setGeometry(QtCore.QRect(100, 50, 311, 31))
        self.contact_email.setObjectName("contact_email")

        self.retranslateUi(ContactWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ContactWindow)

    def retranslateUi(self, ContactWindow):
        _translate = QtCore.QCoreApplication.translate
        ContactWindow.setWindowTitle(_translate("ContactWindow", "ICHAT"))
        self.send_text.setText(_translate("ContactWindow", "Send"))
        self.send_pic.setText(_translate("ContactWindow", "Pic"))
        self.send_file.setText(_translate("ContactWindow", "File"))
        self.send_video.setText(_translate("ContactWindow", "Video"))
        self.method.setItemText(0, _translate("ContactWindow", "Email"))
        self.method.setItemText(1, _translate("ContactWindow", "IChat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Chat), _translate("ContactWindow", "Chat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Files), _translate("ContactWindow", "Files"))
        self.contact_icon.setText(_translate("ContactWindow", "   ICON"))
        self.contact_nickname.setText(_translate("ContactWindow", "NickName"))
        self.contact_email.setText(_translate("ContactWindow", "Email"))

