# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GroupWindow(object):
    def setupUi(self, GroupWindow):
        GroupWindow.setObjectName("GroupWindow")
        GroupWindow.resize(657, 781)
        GroupWindow.setStyleSheet("background-color: rgb(255, 255, 244);")
        GroupWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        GroupWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grouptabs = QtWidgets.QTabWidget(GroupWindow)
        self.grouptabs.setGeometry(QtCore.QRect(0, 90, 661, 691))
        self.grouptabs.setStyleSheet("background-color: rgb(157, 239, 255);")
        self.grouptabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.grouptabs.setTabBarAutoHide(False)
        self.grouptabs.setObjectName("grouptabs")
        self.chat = QtWidgets.QWidget()
        self.chat.setObjectName("chat")
        self.send_text = QtWidgets.QPushButton(self.chat)
        self.send_text.setGeometry(QtCore.QRect(550, 600, 81, 35))
        self.send_text.setStyleSheet("background-color: rgb(255, 181, 162);")
        self.send_text.setObjectName("send_text")
        self.input_msg = QtWidgets.QTextEdit(self.chat)
        self.input_msg.setGeometry(QtCore.QRect(0, 520, 541, 111))
        self.input_msg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_msg.setObjectName("input_msg")
        self.send_pic = QtWidgets.QPushButton(self.chat)
        self.send_pic.setGeometry(QtCore.QRect(10, 480, 109, 35))
        self.send_pic.setStyleSheet("background-color: rgb(217, 255, 193);")
        self.send_pic.setObjectName("send_pic")
        self.send_file = QtWidgets.QPushButton(self.chat)
        self.send_file.setGeometry(QtCore.QRect(130, 480, 109, 35))
        self.send_file.setStyleSheet("background-color: rgb(237, 190, 255);")
        self.send_file.setObjectName("send_file")
        self.scrollArea = QtWidgets.QScrollArea(self.chat)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 651, 471))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 647, 467))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.msgs_box = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.msgs_box.setGeometry(QtCore.QRect(0, 0, 651, 471))
        self.msgs_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.msgs_box.setTitle("")
        self.msgs_box.setObjectName("msgs_box")
        self.scrollArea.setWidget(self.msgs_box)
        self.grouptabs.addTab(self.chat, "")
        self.members = QtWidgets.QWidget()
        self.members.setObjectName("members")
        self.members_box = QtWidgets.QTableWidget(self.members)
        self.members_box.setGeometry(QtCore.QRect(0, 0, 631, 631))
        self.members_box.setStyleSheet("background-color: rgb(234, 255, 205);")
        self.members_box.setObjectName("members_box")
        self.members_box.setColumnCount(0)
        self.members_box.setRowCount(0)
        self.grouptabs.addTab(self.members, "")
        self.files = QtWidgets.QWidget()
        self.files.setObjectName("files")
        self.tableWidget = QtWidgets.QTableWidget(self.files)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 641, 611))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 206, 210);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.grouptabs.addTab(self.files, "")
        self.group_icon = QtWidgets.QLabel(GroupWindow)
        self.group_icon.setGeometry(QtCore.QRect(10, 10, 70, 70))
        self.group_icon.setScaledContents(True)
        self.group_icon.setObjectName("group_icon")
        self.group_name = QtWidgets.QLabel(GroupWindow)
        self.group_name.setGeometry(QtCore.QRect(130, 10, 101, 31))
        self.group_name.setObjectName("group_name")
        self.group_id = QtWidgets.QLabel(GroupWindow)
        self.group_id.setGeometry(QtCore.QRect(130, 50, 79, 31))
        self.group_id.setObjectName("group_id")

        self.retranslateUi(GroupWindow)
        self.grouptabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GroupWindow)

    def retranslateUi(self, GroupWindow):
        _translate = QtCore.QCoreApplication.translate
        GroupWindow.setWindowTitle(_translate("GroupWindow", "GroupChat"))
        self.send_text.setText(_translate("GroupWindow", "Send"))
        self.send_pic.setText(_translate("GroupWindow", "Pic"))
        self.send_file.setText(_translate("GroupWindow", "File"))
        self.grouptabs.setTabText(self.grouptabs.indexOf(self.chat), _translate("GroupWindow", "Chat"))
        self.grouptabs.setTabText(self.grouptabs.indexOf(self.members), _translate("GroupWindow", "Members"))
        self.grouptabs.setTabText(self.grouptabs.indexOf(self.files), _translate("GroupWindow", "Files"))
        self.group_icon.setText(_translate("GroupWindow", "   ICON"))
        self.group_name.setText(_translate("GroupWindow", "GroupName"))
        self.group_id.setText(_translate("GroupWindow", "GroupID"))

