# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(500, 500)
        LoginWidget.setWindowTitle("ICHAT")
        LoginWidget.setStyleSheet("background-color: rgb(200, 255, 185);\n"
"selection-color: rgb(121, 146, 255);")
        LoginWidget.setTabPosition(QtWidgets.QTabWidget.South)
        LoginWidget.setMovable(True)
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.login_btu = QtWidgets.QPushButton(self.Login)
        self.login_btu.setGeometry(QtCore.QRect(170, 430, 109, 35))
        self.login_btu.setStyleSheet("background-color: rgb(88, 255, 144);")
        self.login_btu.setObjectName("login_btu")
        self.remember_btu = QtWidgets.QRadioButton(self.Login)
        self.remember_btu.setGeometry(QtCore.QRect(300, 440, 191, 23))
        self.remember_btu.setStyleSheet("selection-color: rgb(255, 47, 50);\n"
"font: 8pt \"DejaVu Serif\";")
        self.remember_btu.setChecked(False)
        self.remember_btu.setObjectName("remember_btu")
        self.email_cbox = QtWidgets.QComboBox(self.Login)
        self.email_cbox.setGeometry(QtCore.QRect(130, 220, 211, 33))
        self.email_cbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_cbox.setEditable(True)
        self.email_cbox.setObjectName("email_cbox")
        self.label = QtWidgets.QLabel(self.Login)
        self.label.setGeometry(QtCore.QRect(20, 280, 101, 19))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.Login)
        self.label_5.setGeometry(QtCore.QRect(20, 320, 101, 20))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.Login)
        self.label_2.setGeometry(QtCore.QRect(30, 230, 101, 19))
        self.label_2.setObjectName("label_2")
        self.input_email_pass_l = QtWidgets.QLineEdit(self.Login)
        self.input_email_pass_l.setGeometry(QtCore.QRect(130, 310, 211, 33))
        self.input_email_pass_l.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_email_pass_l.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.input_email_pass_l.setObjectName("input_email_pass_l")
        self.input_name_l = QtWidgets.QLineEdit(self.Login)
        self.input_name_l.setGeometry(QtCore.QRect(130, 270, 211, 33))
        self.input_name_l.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_name_l.setObjectName("input_name_l")
        self.usericon = QtWidgets.QLabel(self.Login)
        self.usericon.setGeometry(QtCore.QRect(360, 230, 100, 100))
        self.usericon.setScaledContents(True)
        self.usericon.setObjectName("usericon")
        self.label20 = QtWidgets.QLabel(self.Login)
        self.label20.setGeometry(QtCore.QRect(0, 360, 121, 20))
        self.label20.setObjectName("label20")
        self.input_server_addr_l = QtWidgets.QLineEdit(self.Login)
        self.input_server_addr_l.setGeometry(QtCore.QRect(130, 390, 211, 33))
        self.input_server_addr_l.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_server_addr_l.setText("")
        self.input_server_addr_l.setObjectName("input_server_addr_l")
        self.label10 = QtWidgets.QLabel(self.Login)
        self.label10.setGeometry(QtCore.QRect(40, 400, 81, 20))
        self.label10.setObjectName("label10")
        self.input_server_email_l = QtWidgets.QLineEdit(self.Login)
        self.input_server_email_l.setGeometry(QtCore.QRect(130, 350, 211, 33))
        self.input_server_email_l.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_server_email_l.setText("")
        self.input_server_email_l.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.input_server_email_l.setObjectName("input_server_email_l")
        self.background_l = QtWebEngineWidgets.QWebEngineView(self.Login)
        self.background_l.setGeometry(QtCore.QRect(0, 0, 500, 200))
        self.background_l.setAutoFillBackground(False)
        self.background_l.setStyleSheet("background-color: rgb(55, 168, 255);")
        self.background_l.setUrl(QtCore.QUrl("about:blank"))
        self.background_l.setObjectName("background_l")
        LoginWidget.addTab(self.Login, "")
        self.Register = QtWidgets.QWidget()
        self.Register.setObjectName("Register")
        self.label_3 = QtWidgets.QLabel(self.Register)
        self.label_3.setGeometry(QtCore.QRect(30, 240, 101, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Register)
        self.label_4.setGeometry(QtCore.QRect(30, 300, 101, 19))
        self.label_4.setObjectName("label_4")
        self.input_name_r = QtWidgets.QLineEdit(self.Register)
        self.input_name_r.setGeometry(QtCore.QRect(140, 240, 211, 33))
        self.input_name_r.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_name_r.setObjectName("input_name_r")
        self.input_email_r = QtWidgets.QLineEdit(self.Register)
        self.input_email_r.setGeometry(QtCore.QRect(140, 290, 211, 33))
        self.input_email_r.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_email_r.setObjectName("input_email_r")
        self.register_btu = QtWidgets.QPushButton(self.Register)
        self.register_btu.setGeometry(QtCore.QRect(180, 410, 109, 35))
        self.register_btu.setStyleSheet("background-color: rgb(101, 255, 119);")
        self.register_btu.setObjectName("register_btu")
        self.label_7 = QtWidgets.QLabel(self.Register)
        self.label_7.setGeometry(QtCore.QRect(28, 340, 101, 20))
        self.label_7.setObjectName("label_7")
        self.input_email_pass_r = QtWidgets.QLineEdit(self.Register)
        self.input_email_pass_r.setGeometry(QtCore.QRect(140, 330, 211, 33))
        self.input_email_pass_r.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_email_pass_r.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_email_pass_r.setObjectName("input_email_pass_r")
        self.label15 = QtWidgets.QLabel(self.Register)
        self.label15.setGeometry(QtCore.QRect(10, 380, 121, 20))
        self.label15.setObjectName("label15")
        self.input_server_email_r = QtWidgets.QLineEdit(self.Register)
        self.input_server_email_r.setGeometry(QtCore.QRect(140, 370, 211, 33))
        self.input_server_email_r.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_server_email_r.setText("")
        self.input_server_email_r.setObjectName("input_server_email_r")
        self.background_r = QtWebEngineWidgets.QWebEngineView(self.Register)
        self.background_r.setGeometry(QtCore.QRect(0, 0, 500, 200))
        self.background_r.setUrl(QtCore.QUrl("about:blank"))
        self.background_r.setObjectName("background_r")
        self.register_result = QtWidgets.QLabel(self.Register)
        self.register_result.setGeometry(QtCore.QRect(380, 440, 101, 20))
        self.register_result.setText("")
        self.register_result.setObjectName("register_result")
        LoginWidget.addTab(self.Register, "")

        self.retranslateUi(LoginWidget)
        LoginWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        self.login_btu.setText(_translate("LoginWidget", "Login"))
        self.remember_btu.setText(_translate("LoginWidget", "Re&member Password"))
        self.label.setText(_translate("LoginWidget", "Nick Name:"))
        self.label_5.setText(_translate("LoginWidget", "Email Pass:"))
        self.label_2.setText(_translate("LoginWidget", "        Email:"))
        self.usericon.setText(_translate("LoginWidget", "     ICON"))
        self.label20.setText(_translate("LoginWidget", "Server Email:"))
        self.label10.setText(_translate("LoginWidget", "Address:"))
        LoginWidget.setTabText(LoginWidget.indexOf(self.Login), _translate("LoginWidget", "Login"))
        self.label_3.setText(_translate("LoginWidget", "Nick Name:"))
        self.label_4.setText(_translate("LoginWidget", "        Email:"))
        self.register_btu.setText(_translate("LoginWidget", "Register"))
        self.label_7.setText(_translate("LoginWidget", "Email Pass:"))
        self.label15.setText(_translate("LoginWidget", "Server Email:"))
        LoginWidget.setTabText(LoginWidget.indexOf(self.Register), _translate("LoginWidget", "Register"))

from PyQt5 import QtWebEngineWidgets
