# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 773)
        MainWindow.setStyleSheet("background-color: rgb(75, 231, 255);")
        self.usericon = QtWidgets.QLabel(MainWindow)
        self.usericon.setGeometry(QtCore.QRect(0, 10, 70, 70))
        self.usericon.setScaledContents(True)
        self.usericon.setObjectName("usericon")
        self.nickname = QtWidgets.QLabel(MainWindow)
        self.nickname.setGeometry(QtCore.QRect(120, 10, 221, 19))
        self.nickname.setScaledContents(True)
        self.nickname.setObjectName("nickname")
        self.useremail = QtWidgets.QLabel(MainWindow)
        self.useremail.setGeometry(QtCore.QRect(120, 50, 241, 19))
        self.useremail.setScaledContents(True)
        self.useremail.setObjectName("useremail")
        self.usertabs = QtWidgets.QTabWidget(MainWindow)
        self.usertabs.setGeometry(QtCore.QRect(0, 80, 401, 691))
        self.usertabs.setStyleSheet("background-color: rgb(251, 217, 255);")
        self.usertabs.setObjectName("usertabs")
        self.ichats = QtWidgets.QWidget()
        self.ichats.setObjectName("ichats")
        self.toolBox = QtWidgets.QToolBox(self.ichats)
        self.toolBox.setEnabled(True)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 391, 651))
        self.toolBox.setStyleSheet("background-color: rgb(203, 255, 184);")
        self.toolBox.setObjectName("toolBox")


        self.contacts = QtWidgets.QWidget()
        self.contacts.setGeometry(QtCore.QRect(0, 0, 391, 552))
        self.contacts.setObjectName("contacts")

        self.contacts_box = QtWidgets.QGroupBox(self.contacts)
        self.contacts_box.setEnabled(True)
        self.contacts_box.setGeometry(QtCore.QRect(0, 0, 401, 541))
        self.contacts_box.setTitle("")
        self.contacts_box.setObjectName("contacts_box")
        self.toolBox.addItem(self.contacts, "")


        self.groups = QtWidgets.QWidget()
        self.groups.setGeometry(QtCore.QRect(0, 0, 391, 552))
        self.groups.setObjectName("groups")

        self.groups_box = QtWidgets.QGroupBox(self.groups)
        self.groups_box.setGeometry(QtCore.QRect(0, 0, 391, 541))
        self.groups_box.setTitle("")
        self.groups_box.setObjectName("groups_box")
        self.toolBox.addItem(self.groups, "")
        self.blacklist = QtWidgets.QWidget()
        self.blacklist.setGeometry(QtCore.QRect(0, 0, 391, 552))
        self.blacklist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.blacklist.setAutoFillBackground(False)
        self.blacklist.setObjectName("blacklist")
        self.black_box = QtWidgets.QGroupBox(self.blacklist)
        self.black_box.setGeometry(QtCore.QRect(0, 0, 391, 561))
        self.black_box.setTitle("")
        self.black_box.setObjectName("black_box")
        self.toolBox.addItem(self.blacklist, "")

        self.usertabs.addTab(self.ichats, "")
        self.notify = QtWidgets.QWidget()
        self.notify.setObjectName("notify")
        self.notifies = QtWidgets.QGroupBox(self.notify)
        self.notifies.setGeometry(QtCore.QRect(0, 0, 391, 651))
        self.notifies.setStyleSheet("background-color: rgb(254, 255, 224);")
        self.notifies.setObjectName("notifies")
        self.usertabs.addTab(self.notify, "")
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.widget = QtWidgets.QWidget(self.search)
        self.widget.setGeometry(QtCore.QRect(0, 0, 391, 651))
        self.widget.setStyleSheet("background-color: rgb(255, 176, 169);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 30, 181, 19))
        self.label.setStyleSheet("background-color: rgb(252, 255, 235);")
        self.label.setObjectName("label")
        self.user_search = QtWidgets.QPushButton(self.widget)
        self.user_search.setGeometry(QtCore.QRect(130, 120, 109, 35))
        self.user_search.setStyleSheet("background-color: rgb(117, 159, 255);")
        self.user_search.setObjectName("user_search")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 111, 19))
        self.label_2.setStyleSheet("background-color: rgb(255, 151, 205);")
        self.label_2.setObjectName("label_2")
        self.input_id = QtWidgets.QLineEdit(self.widget)
        self.input_id.setGeometry(QtCore.QRect(12, 70, 371, 33))
        self.input_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_id.setObjectName("input_id")
        self.search_results_table = QtWidgets.QTableWidget(self.widget)
        self.search_results_table.setGeometry(QtCore.QRect(0, 190, 391, 321))
        self.search_results_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.search_results_table.setObjectName("search_results_table")
        self.search_results_table.setColumnCount(0)
        self.search_results_table.setRowCount(0)
        self.usertabs.addTab(self.search, "")
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.setting_widget = QtWidgets.QWidget(self.setting)
        self.setting_widget.setGeometry(QtCore.QRect(0, 0, 401, 661))
        self.setting_widget.setStyleSheet("background-color: rgb(225, 255, 244);")
        self.setting_widget.setObjectName("setting_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.setting_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 30, 231, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.logout = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.logout.setStyleSheet("background-color: rgb(236, 255, 183);")
        self.logout.setObjectName("logout")
        self.gridLayout.addWidget(self.logout, 0, 0, 1, 1)
        self.about = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.about.setStyleSheet("background-color: rgb(255, 213, 140);")
        self.about.setObjectName("about")
        self.gridLayout.addWidget(self.about, 1, 0, 1, 1)
        self.helpme = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.helpme.setStyleSheet("background-color: rgb(255, 87, 53);")
        self.helpme.setObjectName("helpme")
        self.gridLayout.addWidget(self.helpme, 2, 0, 1, 1)
        self.usertabs.addTab(self.setting, "")

        self.retranslateUi(MainWindow)
        self.usertabs.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ICHAT"))
        self.usericon.setText(_translate("MainWindow", "  ICON"))
        self.nickname.setText(_translate("MainWindow", "Name"))
        self.useremail.setText(_translate("MainWindow", "Email"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.contacts), _translate("MainWindow", "Contacts"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.groups), _translate("MainWindow", "Groups"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.blacklist), _translate("MainWindow", "Blacklist"))
        self.usertabs.setTabText(self.usertabs.indexOf(self.ichats), _translate("MainWindow", "IChats"))
        self.notifies.setTitle(_translate("MainWindow", "GroupBox"))
        self.usertabs.setTabText(self.usertabs.indexOf(self.notify), _translate("MainWindow", "Notify"))
        self.label.setText(_translate("MainWindow", "User Email / GroupID"))
        self.user_search.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Click to Add"))
        self.usertabs.setTabText(self.usertabs.indexOf(self.search), _translate("MainWindow", "Search"))
        self.logout.setText(_translate("MainWindow", "Logout"))
        self.about.setText(_translate("MainWindow", "About"))
        self.helpme.setText(_translate("MainWindow", "HelpMe"))
        self.usertabs.setTabText(self.usertabs.indexOf(self.setting), _translate("MainWindow", "Setting"))

